nodeLinker: node-modules
npmScopes:
  "sapo":
    npmRegistryServer: https://git.dktsoft.com:2008/api/v4/projects/2584/packages/npm
    npmAlwaysAuth: true
    npmAuthToken: glpat-s2UgerVWzM64wq7rgrXM